---
apiVersion: v1
kind: Service
metadata:
  name: <%=artifact%>-svc
  labels:
    group: leptoncli
spec:
  type: ClusterIP
  selector:
    app: <%=artifact%>
  ports:
    - port: 80
      targetPort: <%=portNumber%>
